service: charles-vacine-ja
useDotenv: true

plugins:
  - serverless-python-requirements

custom:
  pythonRequirements:
    pythonBin: python3

provider:
  name: aws
  runtime: python3.8
  region: sa-east-1
  stage: dev
  lambdaHashingVersion: 20201221
  environment:
    SENDER_EMAIL: ${env:SENDER_EMAIL}
    DESTINATION_EMAIL: ${env:DESTINATION_EMAIL}
    PEOPLE: ${env:PEOPLE}

package:
  individually: true
  patterns:
    - "!node_modules/**"
    - "!package-lock.json"
    - "!.venv/**"
    - "!.env"
    - "!env.example"
    - "!README.md"

functions:
  - ${file(src/functions/pdf_reader/function.yml)}