service: charles-vacine-ja
useDotenv: true

plugins:
  - serverless-python-requirements

custom:
  pythonRequirements:
    pythonBin: python3

provider:
  name: aws
  runtime: python3.8
  region: sa-east-1
  stage: dev
  lambdaHashingVersion: 20201221
  environment:
    AUTH_AWS_ACCESS_KEY_ID: ${env:AUTH_AWS_ACCESS_KEY_ID}
    AUTH_AWS_SECRET_ACCESS_KEY: ${env:AUTH_AWS_SECRET_ACCESS_KEY}
    AUTH_AWS_REGION_NAME: ${env:AUTH_AWS_REGION_NAME}
    SENDER_EMAIL: ${env:SENDER_EMAIL}
    DESTINATION_EMAIL: ${env:DESTINATION_EMAIL}
    CPFS: ${env:CPFS}
    NAMES: ${env:NAMES}

package:
  individually: true
  patterns:
    - "!node_modules/**"
    - "!package-lock.json"
    - "!.venv/**"
    - "!.env"
    - "!env.example"
    - "!README.md"

functions:
  - ${file(src/functions/checker/function.yml)}
  - ${file(src/functions/checker/tester.yml)}