name: Deploy
on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: '3.8'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Install serverless plugins
        run: |
          npm install
      - name: Deploy
        uses: serverless/github-action@master
        with:
          args: deploy
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AUTH_AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AUTH_AWS_SECRET_ACCESS_KEY }}
          AWS_REGION_NAME: ${{ secrets.AUTH_AWS_REGION_NAME }}
          AUTH_AWS_ACCESS_KEY_ID: ${{ secrets.AUTH_AWS_ACCESS_KEY_ID }}
          AUTH_AWS_SECRET_ACCESS_KEY: ${{ secrets.AUTH_AWS_SECRET_ACCESS_KEY }}
          AUTH_AWS_REGION_NAME: ${{ secrets.AUTH_AWS_REGION_NAME }}
          SENDER_EMAIL: ${{ secrets.SENDER_EMAIL }}
          DESTINATION_EMAIL: ${{ secrets.DESTINATION_EMAIL }}
          CPFs: ${{ secrets.CPFs }}
          NAMES: ${{ secrets.NAMES }}
